---
title: "assignment_2"
author: "Andri"
date: "2025-11-27"
output: pdf_document
---

```{r}
library(xtable)
use<-c("no","no", "yes","yes")
per<-c("no","yes","no","yes")
n<-c(265,148,75,22)
data21 <- data.frame(use,per,n)

data21$use <- as.factor(data21$use)
data21$per <- as.factor(data21$per)
model21<-glm(per~use, weights =n, family = binomial(link=logit), data=data21)

```

```{r}
logdos<-c(-7.60,-6.22,-4.60,-3.00,-1.39,0.92)
n<-c(18,19,28,32,28,40)
x<-c(1,2,4,9,12,32)
data22 <- data.frame(logdos,x,n)
data22
model22<-glm(x/n~logdos, family = binomial(link=logit), weights=n, data=data22)
summary(model22)
vcov(model22)
confint.default(model22,level=0.95)

```
```{r}
zw <- 0.52037/0.08502
2*(1-pnorm(zw))
```

```{r}
x <- c(-1.38629)
pred <- predict(model22, newdata = data.frame(logdos = -1.39), type="link", se.fit=TRUE)
fit <- pred$fit
se <- pred$se.fit

z <- qnorm(0.975)
lower_logit <- fit - z*se
upper_logit <- fit + z*se

lower_prob <- plogis(lower_logit)
upper_prob <- plogis(upper_logit)
pred_prob <- plogis(fit)

pred_prob
lower_prob
upper_prob
```
```{r}
zw <- 0.52037^2 / 0.007229089
1-pchisq(zw, df=1)
```



```{r}
data22
```

```{r}
multiplier <- c(1, 10, 100, 1000)
var_beta_0 <- c()
var_beta_1 <- c()
cov_b0_b1 <- c()
for (i in 1:length(multiplier)) {
  dat <- data22
  dat$n <- dat$n * multiplier[i]
  dat$x <- dat$x * multiplier[i]
  model <- glm(x/n ~ logdos,
               family = binomial(link="logit"),
               weights = n,
               data=dat)
  conf_matrix <- vcov(model)
  var_beta_0[i] <- conf_matrix[1,1]
  var_beta_1[i] <- conf_matrix[2,2]
  cov_b0_b1[i] <- conf_matrix[1,2]
}
final_table <- data.frame(multiplier, var_beta_0, var_beta_1, cov_b0_b1)
final_table
```


